### ISSUE TITLE
Translation NuGet packages

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore.Translations#10]
After talking with @sebastienros in gitter, I started working on a power shell script that automate creation and publishing for the translation NuGet packages as the following:

1. Creating a NuGet packages

- [X] Create `appveyor.yaml`
- [x] Create power shell script `pack.ps1` for generating NuGet packages for all translations that are located in `Localization` folder
- [x] Integrate `pack.ps1` with CI/CD

2. Publishing a NuGet packages
- [ ] Add NuGet API key to `appveyor.yml`

**Comment by hishamco** [comment]
Some questions for step 1:

- How can we determine the version number that will be used for each package, AFAIK if it's an assembly we can easily read the `AssemblyInfo`
- NuGet packages are created manually with powershell - without using NuGet.exe - this may lead to some complexities specially in generated a `PSMDCP` file

/cc @sebsatienros @agriffard

**Comment by sebastienros** [comment]
You can use `$env:BuildNumber` in your script. It's copying it from appveyor if you look at the script

**Comment by hishamco** [comment]
> You can use $env:BuildNumber 

I was thinking about that, but how it can ensure it's `1.0.0` or `1.1.0` if we merge to master?

**Comment by hishamco** [comment]
> NuGet packages are created manually with powershell - without using NuGet.exe - this may lead to some complexities specially in generated a PSMDCP file

Seems it's not required if I didn't add files tag in the `.nuspec`, time to test in my branch ..

**Comment by hishamco** [comment]
FYI I moved the version number into `appveyor.yml`, so each time we release a build we need to change the version number there. We can look if there's way to increment the version when we merge to `l10n_master branch`

**Comment by hishamco** [comment]
Step 2 will be done by you @sebastienros

**Comment by hishamco** [comment]
Woohoo it seems I can update the version automatically when a PR is pushed to master or when a version tag is created

**Comment by hishamco** [comment]
Seems we forgot to close this one :)
