### ISSUE TITLE
Update PO Extractor Tool 1.1.0

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore.Translations#104]
We need to update the PO Extractor tool to `1.1.0` or `1.2.0` which will ship ASAP before shipping OC `2.0.0` there are few enhancements to support new C# features

https://www.nuget.org/packages/OrchardCoreContrib.PoExtractor/1.1.0

/cc @agriffard

**Comment by agriffard** [comment]
OK, tell me when it is available.
I will have to update the .pot files before the 2.0 release.

**Comment by hishamco** [comment]
https://www.nuget.org/packages/OrchardCoreContrib.PoExtractor/1.1.0 is LIVE you can update it right now. Once I will release `1.2.0` which probably should be done next I will inform you

Thanks

**Comment by hishamco** [comment]
@agriffard could you please handle `1.1.0` update ASAP

**Comment by agriffard** [comment]
> @agriffard could you please handle `1.1.0` update ASAP

I updated my tool locally to `1.1.0` but I don't really understand what you want me to do, then?

**Comment by hishamco** [comment]
I mean update it locally and publish the POT, if you already did you can close this, and then I will file a new issue once `1.2.0` released

**Comment by agriffard** [comment]
.pot files updated and synced on Crowdin.

**Comment by hishamco** [comment]
I will close this while it's done, please let me know if you find an issue in the translations
