### ISSUE TITLE
Add AppVeyor badge

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore.Translations#11]

**Comment by hishamco** [comment]
@sebastienros could please send me AppVeyor project link, coz I'm blocked by this one. I need to see what's going on during CI/CD

**Comment by sebastienros** [comment]
I told you to create a PR, then the link will be there

**Comment by hishamco** [comment]
How?!!

**Comment by hishamco** [comment]
AFAIK, we need to add the AppVeyor badge by self. I know that the CI/CD will work now after you added the `appveyor.yaml`, but I'm asking for the project link

Hope you got what I'm asking for?

**Comment by hishamco** [comment]
⌚️

**Comment by sebastienros** [comment]
Let's say you had created a PR as suggested ... so I'll take the one that has been created by crowdin, you are lucky: https://github.com/OrchardCMS/OrchardCore.Translations/pull/12

On this page you see the "Checks", which are generated by appveyor:
![image](https://user-images.githubusercontent.com/1165805/64053007-78172a00-cb35-11e9-8018-a625aedef4cc.png)

You click on the link:
https://ci.appveyor.com/project/SebastienRos/orchardcore-translations/builds/27065963

Bingo!

Is that what you wanted?

**Comment by hishamco** [comment]
Ya, believe it or not I guess all the possibilities of the link above my mistake was I used orchardcore.translation 😄 

thanks

**Comment by hishamco** [comment]
BTW why this https://ci.appveyor.com/project/SebastienRos/orchardcore-translations/branch/l10n-pack not found or denied, is there a settings that you need to add to include another branch? If YES, please add mine `l10n-pack`

FYI I already updated `appveyor.yaml` waiting to see the log in AppVeyor

**Comment by sebastienros** [comment]
I am only building custom branches if they are PRs, so create this PR and your branch will be built. If you don't I will click the button for you.

**Comment by hishamco** [comment]
Did you mean create a PR in my branch?

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore.Translations/pull/13

**Comment by hishamco** [comment]
Seems I created before you on I10n_master :)

Thanks

**Comment by hishamco** [comment]
Fixed in commit https://github.com/OrchardCMS/OrchardCore.Translations/commit/bb4613c2d14ca25719ee96d6d4e543cf65068998
