### ISSUE TITLE
Change translations version to 1.0.0-rc1 

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore.Translations#28]
This is just a reminder for us to change the qualifier from `beta-xxxx` to `rc1` in the `pack.ps1` before we merge dev branch into master

/cc @sebastienros

**Comment by sebastienros** [comment]
Do you think you could see if the translations are loaded only once in memory, even with multiple tenants, and also if they are only loaded for the cultures that are actually in use? If not the case, it might be too impactful on perf, and we would not use the meta package by default.

**Comment by hishamco** [comment]
That's what I mentioned before in another, I will try this, but frankly I'm not specialist to measure such perf, but I will struggle

**Comment by jtkech** [comment]
After a quick look, seems that all transaltions from all providers are loaded an cached per tenant. Yes, we would need some static cache shared across tenants as we do for other things **as shape tables**. I think also for the translations provided by a given module that may be enabled in multiple tenants.

Only tenant specific translations would needs to be cached per tenant.
