### ISSUE TITLE
Delete non translated cultures from Crowdin

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore.Translations#34]
@agriffard I notice that we have 14 cultures with 0%, this indicates that no one interested yet to translate these cultures. I suggest to delete them from Crowdin and encourage to support their languages.

With that anyone can file an issue if he/she interest to translate a new culture that's not listed in Crowdin. In this we can ensure at least there 're active members on some translations to be fully supported by OrchardCore.Translation.* packages

/cc @sebastienros

**Comment by agriffard** [comment]
Well, I could remove the cultures that have 0% of translation on Crowdin.
The idea was simply to activate the same cultures already available in O1.

If people see that a culture needs translations, they could be more eager to contribute.
For example, last week a Greek contributor started to translate the resources.

First, I would suggest to find a way to gather more contributors.
Ex: Make a tweet on the OrchardCMS account to ask for contributors.

**Comment by hishamco** [comment]
> The idea was simply to activate the same cultures already available in O1.

I see

> Make a tweet on the OrchardCMS account to ask for contributors.

This is a good option too

**Comment by hishamco** [comment]
FYI I notice if you change anything in Crowdin a PR will be created ASAP, that bad thing that I personally dislike, the `pack.ps1` script will generate a NuGet packages for every culture in the repo, where some of them are actually untranslated at all

**Comment by hishamco** [comment]
Still I don't think we need to publish untranslated packages

**Comment by hishamco** [comment]
Again I don't see any value to push NuGet packages that are not contain a proper translations for some cultures

/cc @sebastienros

**Comment by sebastienros** [comment]
Then don't process the translations packages that are empty. So the meta package contains only the ones with content. Fine.

**Comment by sebastienros** [comment]
We definitely don't want to remove them from crowdin.

**Comment by hishamco** [comment]
> Then don't process the translations packages that are empty. So the meta package contains only the ones with content. Fine.

I don't think they are empty, it contains the default translations (en)

**Comment by sebastienros** [comment]
I am sure you'll figure out a way to find that there is no custom translation, like the files are the same as the English one for instance. Or maybe there is another way to tell, cloning the English po files and calculating the crc32 of each file to compare with each other language.

**Comment by hishamco** [comment]
No worry, I will try to handle it

**Comment by hishamco** [comment]
> like the files are the same as the English one for instance

This is not easy as you think, because there's no English translation 😄
