### ISSUE TITLE
msgctxt not working

### ISSUE THREAD

**Issue by Ahmed-Galal85** [OrchardCMS/OrchardCore.Translations#36]
When using "msgctxt" translation not working, should be "#. msgctxt" for working with me
please help

> #: Text.Web\Areas\eg\ViewModels\TestVM.cs:49
> #. [Display(Name = "اسم النموذج انجليزي")]
> msgctxt "Test.Web.Areas.eg.ViewModels.Index"
> msgid "اسم النموذج انجليزي"
> msgstr "The model name is English"

**Comment by hishamco** [comment]
Seems you create the .po file yourself

> When using "msgctxt" translation not working, should be "#. msgctxt" for working with me

If you have a look to all the translations they are using "msgctxt" not ".msgctxt", seems you did something wrong

Could you please write down your TestVM.cs code here, I expect its a namespace issue

**Comment by Ahmed-Galal85** [comment]
Full Example
```
#: App.Web\Areas\eg\ViewModels\AttachmentTemplateVM.cs:46
#. [Display(Name = "اسم النموذج عربي")]
msgctxt "App.Web.Areas.eg.ViewModels.AttachmentTemplateVM.Index"
msgid "اسم النموذج عربي"
msgstr "Model Name Arabic"
```
  ```
public static class AttachmentTemplateVM
    {
        public class Index
        {
            [Display(Name = "اسم النموذج عربي")]
            public string NameArabic { get; set; }
        }
     }
```

thanks

**Comment by hishamco** [comment]
Please the namespace

Is the inner class by intention?

**Comment by Ahmed-Galal85** [comment]
> 
> 
> Please the namespace
> 
> Is the inner class by intention?

I update example
I want to translate inner class

**Comment by hishamco** [comment]
If you have a repo to reproduce the bug will be nice

**Comment by Ahmed-Galal85** [comment]
https://github.com/Ahmed-Galal85/TestAppForLocalization/tree/master/App.Web/App.Web

**Comment by hishamco** [comment]
@lukaskabrt is the inner classes support by your extractor tool?

**Comment by Ahmed-Galal85** [comment]
> 
> 
> @lukaskabrt is the inner classes support by your extractor tool?

Yes, I Change in your project "[POExtract](https://github.com/lukaskabrt/PoExtractor)"  for extract data annotations and fully namespace

**Comment by lukaskabrt** [comment]
> @lukaskabrt is the inner classes support by your extractor tool?

I haven't testes inner classes but it shouldn't be a problem. PoExtractor traverses the whole AST, but there isn't any built-in extractor for strings in data attributes.

**Comment by hishamco** [comment]
I think I need to test if it's a localisation issue

**Comment by hishamco** [comment]
Moved to https://github.com/OrchardCMS/OrchardCore/issues/4664
