### ISSUE TITLE
Use GitHub packages feature

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore.Translations#37]
We can do the same thing that we did in Orchard Core repo

**Comment by hishamco** [comment]
An updates on this?

/cc @agriffard @sebastienros

**Comment by hishamco** [comment]
@agriffard can we consider this before 1.0.0 release?

**Comment by sebastienros** [comment]
GH packages requires authentication so it's not very usable

**Comment by hishamco** [comment]
It requires GITHUB_TOKEN, I already did something similar here https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/dev/.github/workflows/build.yml
