### ISSUE TITLE
You should create correct culture for Serbian on Crowdin

### ISSUE THREAD

**Issue by neman** [OrchardCMS/OrchardCore.Translations#39]
You should create correct culture for Serbia on **Crowdin**

The correct ones are

- Serbian Latin sr-Latn-RS

- Serbian Cyrillic sr-Cyrl-RS

CS is for former state Serbia and Montenegro, legacy Culture

https://www.iso.org/obp/ui/#search/code/

_Originally posted by @neman in https://github.com/OrchardCMS/OrchardCore/issues/4475#issuecomment-538435145_

**Comment by neman** [comment]
@agriffard Can I create PR for this?

**Comment by agriffard** [comment]
The custom cultures have been created on Crowdin:
https://crowdin.com/project/orchard-core/sr-cyrl-rs
https://crowdin.com/project/orchard-core/sr-latn-rs

Translate the strings on Crowdin and they will be synced on this repository.

**Comment by neman** [comment]
Event though in source code are different folder names?

![image](https://user-images.githubusercontent.com/350314/69483640-0e53a700-0e2a-11ea-8d94-527389d311f4.png)

**Comment by neman** [comment]
The flag and the names should be the same. You should delete the previous ones, there is no need to have four (4) Serbian translations

![image](https://user-images.githubusercontent.com/350314/69484069-2843b880-0e2f-11ea-82ca-2cfb4f32e6fc.png)

**Comment by agriffard** [comment]
They are custom cultures on Crowdin so there won't be any flag.
They are now synced on this repository.

Translate them on Crowdin and they will be synced here.

**Comment by hishamco** [comment]
@sebastienros can delete the old translations NuGet packages for related cultures from MyGet & NuGet coz they are no longer needed

**Comment by hishamco** [comment]
I will close this, while it's done, Seb please don't forget to have a look to my last comment
