### ISSUE TITLE
Reset Password validation message is not localized.

### ISSUE THREAD

**Issue by nakamura2000** [OrchardCMS/OrchardCore.Translations#60]
"New password is required." for "OrchardCore.Users.ViewModels.ChangePasswordViewModel" is missing
in "OrchardCore.Users.po".

Password Reset validation message is localized by different message context ( ChangePasswordViewModel ) .
so msgctxt should be "OrchardCore.Users.ViewModels.ChangePasswordViewModel ".

source code : OrchardCore.Users\ViewModels\ResetPasswordViewModel.cs
localization file : OrchardCore.Users.po

message not used :

> #: OrchardCore.Users\ViewModels\ResetPasswordViewModel.cs:35
> #. yield return new ValidationResult(S["New password is required."], new[] { nameof(NewPassword) });
> msgctxt "OrchardCore.Users.ViewModels.ResetPasswordViewModel"
> msgid "New password is required."
> msgstr ""

this message is similar but not same:

> #. yield return new ValidationResult(S["Password is required."], new[] { nameof(Password) });
> #: OrchardCore.Users\ViewModels\ChangePasswordViewModel.cs:29
> msgctxt "OrchardCore.Users.ViewModels.ChangePasswordViewModel"
> msgid "Password is required."
> msgstr ""

**Comment by agriffard** [comment]
I still need to generate the new .po files.

**Comment by hishamco** [comment]
I though you forgot to close it. BTW I see such bug happen frequently, I may create a new analyzer for that

**Comment by hishamco** [comment]
@agriffard can we close this?
