### ISSUE TITLE
Nuget package properties

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Translations#61]
See https://github.com/OrchardCMS/OrchardCore/pull/7237 and apply the same changes

**Comment by hishamco** [comment]
When should this be ready, coz I need finish some PRs on OC first, then I can handle this

**Comment by agriffard** [comment]
> When should this be ready, coz I need finish some PRs on OC first, then I can handle this

Once OrchardCMS/OrchardCore#7237 is merged and before the release.

**Comment by agriffard** [comment]
@ns8482e Can you please help us on this one?

**Comment by ns8482e** [comment]
@agriffard Created PR #69
