### ISSUE TITLE
Some inconsistencies and errors in Russian translation

### ISSUE THREAD

**Issue by ivaskonyanhec** [OrchardCMS/OrchardCore.Translations#68]
I found some inconsistencies and errors in Russian translation I want to share:

_OrchardCore.Forms.po Line: 695_
`Название поля, для которого это утверждение.` -> `Имя поля, для которого предназначена эта проверка.`

_OrchardCore.Autoroute.po Line: 115_
`Сделать домашней` -> `Сделать домашней страницей`

_OrchardCore.ContentFields.po Line: 494_
``->`Используется ли URL-адрес при выборе из «Вставить медиа» (по умолчанию вставляется шорткод).`

_OrchardCore.ContentFields.po Line: 506_
`Документация по вариантам` -> `Документация по опциям`

_OrchardCore.ContentFields.po Line: 1002_
`Точность` -> `Масштаб`

_OrchardCore.ContentLocalization.po Line: 105_
`Установить Cookie` -> `Установить куки`

_OrchardCore.ContentTypes.po Line: 57_
`Название топика не может быть пустым.` -> `Отображаемое имя не может быть пустым.`

_OrchardCore.ContentTypes.po Line: 277_
`Перепользуемая` -> `Переиспользуемая`

_OrchardCore.Infrastructure.po Line: 37_
`Оргументы команды \"{0}\" не совпадают с определением команды` -> `Аргументы команды \"{0}\" не совпадают с определением команды`

_OrchardCore.Infrastructure.po Line: 49_
`Несколько команд нашли соответствующие аргументы \"{0}\". Доступны команды: {1}.` -> `Несколько команд найдено для соответствующих аргументов \"{0}\". Доступные команды: {1}.`

**Comment by hishamco** [comment]
Thanks @ivaskonyanhec for reporting this, could you please fix them in Crowdin

**Comment by ivaskonyanhec** [comment]
Yep, sure. I've sent requests to join Russian and Ukrainian translations for this project. Please approve.

**Comment by agriffard** [comment]
Approved on Crowdin.
