### ISSUE TITLE
the pt package is not referenced from All

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore.Translations#79]
https://github.com/OrchardCMS/OrchardCore/issues/10150

**Comment by hishamco** [comment]
I will have a look

**Comment by sebastienros** [comment]
Probably because we don't reference it by design:

https://github.com/OrchardCMS/OrchardCore.Translations/blob/main/cultures.json#L139

So maybe we should include it since it has 17%. I don't remember what we said should be the threshold.

**Comment by hishamco** [comment]
Ya, also we talked about reduce the culture that are less than 25% or 15%, I will review our conversation, may be it need to be referenced manually and not included in all translations

**Comment by hishamco** [comment]
Seb as you said it's by design, the culture should have more than 50%, for example https://github.com/OrchardCMS/OrchardCore.Translations/pull/58

I will scan all the cultures in the Crowdin, and update the `cultures.json` if it's required

**Comment by hishamco** [comment]
After a quick I think we need to include the cultures with 25% or more, coz many translations have been added since then, some culture may need to be excluded, so if you agree to include those with 25% I will push a PR soon ...
