### ISSUE TITLE
 Chinese short names

### ISSUE THREAD

**Issue by Gsonovb** [OrchardCMS/OrchardCore.Translations#89]
Hi

Simplified Chinese abbreviation: `zh-Hans` , `zh-Hans-CN` , `zh-CN`

I've seen the official documentation that says `zh-CN` is the same as  `zh-Hans-CN` on Windows, but Unix returns a different result, which means running in a Docker container gives a different result.

https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=net-6.0

**Comment by Skrypt** [comment]
This is a quite redundant issue that I never got an answer from @agriffard to know if it is possible to have these.

**Comment by Gsonovb** [comment]
Hi

I propose to rename "zh-CN" to "zh-Hans" and "zh-TW" to "zh-Hant",

 "zh-Hans" is added in the settings panel. I need to rename the localized directory.

**Comment by hishamco** [comment]
@Gsonovb we already did that, please check [this](https://github.com/OrchardCMS/OrchardCore.Translations/tree/main/Localization)

**Comment by Gsonovb** [comment]
> @Gsonovb we already did that, please check [this](https://github.com/OrchardCMS/OrchardCore.Translations/tree/main/Localization)

thanks!
