### ISSUE TITLE
PO Extractor Tool

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore.Translations#93]
@agriffard I'd like to inform you that the `PoExtractor` has been moved into Orchard Core Contrib (OCC) I maintaining the library right now, fixing issues and planning to publish a NuGet package in the upcoming days. I might change the package name, so I need to coordinate with you regarding crowdin. When and how you are using this tool to generate the resources?

**Comment by agriffard** [comment]
I generate the .pot files before a Release, update them in this repo and then call a `Sync` button in Crowdin.

**Comment by hishamco** [comment]
So, you did it manually at your end, right?

**Comment by agriffard** [comment]
I install the tool and execute `extractpo-oc D:\Orchard\OrchardCore C:\temp\OrchardCore --liquid` to generate the .pot files.

**Comment by hishamco** [comment]
FYI I just release a preview release after adding few enhancements and bug fixing https://www.nuget.org/packages/OrchardCoreContrib.PoExtractor/1.0.0-preview

Please have a try, your feedback are always welcome

BTW check the `README.md` there 're few updated in the tool name and CLI options

**Comment by hishamco** [comment]
@agriffard did you update this one?

**Comment by agriffard** [comment]
I generated the pot files last week but I still had the preview and it messed up the files so I reverted them, updated to 1.0 and with the help from Crowdin support, everything wen back correctly.

**Comment by agriffard** [comment]
> Do you mean it messed up with https://www.nuget.org/packages/OrchardCoreContrib.PoExtractor/1.0.1 ?

No, with https://www.nuget.org/packages/OrchardCoreContrib.PoExtractor/1.0.0-preview

**Comment by hishamco** [comment]
I see, please use the latest version, let me know if there's an issue

**Comment by hishamco** [comment]
@agriffard I need to reproduce the issue, so I can fix the bug if there's

**Comment by agriffard** [comment]
No trouble anymore with https://www.nuget.org/packages/OrchardCoreContrib.PoExtractor/1.0.1
I updated the .pot files in prevision of OC 1.7.

**Comment by hishamco** [comment]
LGTM, I will close this one
